project:
  type: website
  render:
    - "*.qmd"
    - "*.md"
    - "*.ipynb"

execute:
  freeze: auto

website:
  title: "DEMO SITE"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: website/about.qmd
        text: About
      - href: api-client/test2.ipynb
        text: "Test NB"

format:
  html:
    theme: cosmo
    css: website/styles.css
    toc: true


