project:
  type: website
  render:
    - "*.qmd"
    - "*.md"
    - "*.ipynb"

execute:
  freeze: auto

website:
  title: "EODH Training Materials"
#  cookie-consent:
#    style: headline
#    palette: dark
  sidebar:
    style: "docked"
    search: true
    contents:
      - text: "Home"
        href: index.qmd
      - text: "About"
        href: website/about.qmd
      - section: "API Client (pyeodh)"
        contents: 
          - text: "Searching the Resource Catalogue"
            href: api-client/2_ResourceCatalog.ipynb
      - section: "Presentations"
        contents: 
          - text: "DEFRA 2024-09"
            href: presentations/DEFRA/202409_Defra.ipynb

format:
  html:
    theme:
      light: cosmo #flatly
      dark: darkly
    #css: styles.css
    toc: true