project:
  type: website
  render:
    - "*.qmd"
    - "*.md"
    - "*.ipynb"

execute:
  freeze: auto

website:
  title: "EODH Training Materials"
#  cookie-consent:
#    style: headline
#    palette: dark
  navbar:
    tools:
      - icon: github
        menu:
          - text: Source Code
            href:  https://github.com/orgs/EO-DataHub/repositories
          - text: Community discussion
            href:  https://github.com/EO-DataHub/eodh-training/discussions
  sidebar:
    style: "docked"
    search: true
    collapse-level: 1
    contents:
      - text: "Home"
        href: index.qmd
      - text: "About"
        href: website/about.qmd
        # Platform section
      - section: "Hub Platform"
        contents: 
          - text: "EODH Platform Introduction"
            href: platform/1_Intro.ipynb
          - text: "EODH Platform Components"
            href: platform/2_Components.ipynb
        # API Client Section
      - section: "Simplifying access - pyeodh"
        contents: 
          - text: "What is pyeodh?"
            href: api-client/1_ClientIntro.md
          - text: "Using the Resource Catalogue"
            href: api-client/2_ResourceCatalog.ipynb
          - text: "Running Workflows"
            href: api-client/3_WorkflowRunner.ipynb
          - text: "Using Mapping Services"
            href: api-client/4_Services.ipynb
        # Workflows Section
      - section: "Creating Workflows - eoap-gen"
        contents: 
          - text: "Workflow Introduction"
            href: workflows/1_Workflows.ipynb
          - text: "EO App Packages"
            href: workflows/2_EOAP.md
          - text: "Using eoap-gen"
            href: workflows/3_eoapgen.ipynb
          - text: "User Example: coherence"
            href: workflows/4_UserExample1.ipynb
          - text: "User Example: temporal mosaics"
            href: workflows/5_UserExample2.ipynb
        # GIS Section
      - section: "GIS interface - QGIS plugin"
        contents: 
          - text: "QGIS Plugin Introduction"
            href: plugin/1_Introduction.md
          - text: "Running A Workflow"
            href: plugin/2_RunningWorkflows.md
        # Examples Section
      - section: "Science & code examples"
        contents: 
          - text: "Data cubes"
            href: science/1_DataCubes.ipynb
          - text: "Commercial data"
            href: science/2_Commercial.ipynb
        # Presentations and Demos
      - section: "Presentations"
        contents: 
          - text: "DEFRA Data Discovery"
            href: presentations/DEFRA/1_202409_Defra_DataDiscovery.ipynb
          - text: "DEFRA Data Processing"
            href: presentations/DEFRA/2_202409_Defra_DataProcessing.ipynb
          - text: "DEFRA Data Analysis"
            href: presentations/DEFRA/3_202409_Defra_DataAnalysis.ipynb        

format:
  html:
    theme:
      light: flatly
      dark: darkly
    #css: styles.css
    toc: true