project:
  type: website
  render:
    - "*.qmd"
    - "*.md"
    - "*.ipynb"

execute:
  freeze: auto

website:
  title: "EODH Training Materials"
  cookie-consent:
    style: headline
    palette: dark
  navbar:
    tools:
      - icon: github
        menu:
          - text: Source Code
            href:  https://github.com/orgs/EO-DataHub/repositories
          - text: Community discussion
            href:  https://github.com/EO-DataHub/eodh-training/discussions
  sidebar:
    style: "docked"
    search: true
    collapse-level: 1
    contents:
      - text: "Home"
        href: index.qmd
      - text: "About"
        href: website/about.qmd
      - section: "Hub Platform"
        contents: 
          - text: "Some info"
            href: platform/1_hello.ipynb
      - section: "Simplifying access - pyeodh"
        contents: 
          - text: "Searching the Resource Catalogue"
            href: api-client/2_ResourceCatalog.ipynb
      - section: "Creating Workflows - eoap-gen"
        contents: 
          - text: "Workflow Introduction"
            href: workflows/1_workflows.ipynb
      - section: "GIS interface - QGIS plugin"
        contents: 
          - text: "QGIS Plugin Introduction"
            href: plugin/1_Introduction.md
          - text: "Running A Workflow"
            href: plugin/2_RunningWorkflows.md
      - section: "Science examples"
        contents: 
          - text: "QGIS Plugin Introduction"
            href: science/1_CodeSnippets.ipynb
      - section: "Presentations"
        contents: 
          - text: "DEFRA Data Discovery"
            href: presentations/DEFRA/1_202409_Defra_DataDiscovery.ipynb
          - text: "DEFRA Data Processing"
            href: presentations/DEFRA/2_202409_Defra_DataProcessing.ipynb
          - text: "DEFRA Data Analysis"
            href: presentations/DEFRA/3_202409_Defra_DataAnalysis.ipynb        

format:
  html:
    theme:
      light: flatly
      dark: darkly
    #css: styles.css
    toc: true