project:
  type: website
  render:
    - "*.qmd"
    - "*.md"
    - "*.ipynb"

execute:
  freeze: auto

website:
  title: "EODH Training Materials"
  sidebar:
    style: "docked"
    search: true
    contents:
      - text: "Home"
        href: index.qmd
      - text: "About"
        href: website/about.qmd
      - section: "API Client (pyeodh)"
        contents: 
          - text: "Searching the Resource Catalogue"
            href: api-client/2_ResourceCatalog.ipynb

format:
  html:
    theme: litera
    css: website/styles.css
    toc: true


