---
title: "About"
---

# What is the EODH
The Earth Observation Data Hub is:

“A UK Pathfinder project delivering access to Earth Observation (EO) data for effective decisionmaking across government, business and academia. The Earth Observation DataHub (EODH) brings together an expert project delivery team and industrial partners in an ambitious project… Users of the Hub will be able to explore areas of interest in the UK and across the globe… It will also enable selected users to support their own analyses, services and tools using the Hub’s workflow and compute environments.”

More details can be found online at https://eodatahub.org.uk/

Components of the Hub include: 

* A Resource Catalogue - a STAC compliant catalogue of open and commercial satellite imagery, climate data, model results, workflows and more 
* A Workflow Runner - a dedicated piece of cloud infrastructure to horizontally scale workflow requirements 
* A Web Presence - an intuitive user interface to allow account management, data discovery and mapping 
* An App Hub - a science portal providing access to a Jupyter lab environment

# Resources on this website
There are a number of resources on this website. The site is a reflection of the training materials repository on GitHub so all Jupyter notebooks can also be discovered there. 

## Using this website
The code in a given Jupyter notebook can either be copied and run on the Python command-line or in a script. The entire notebook can be downloaded and run wholly or stepwise through each cell. The code has been tested at the time of creation and will work with the required import packages. 

If there are any issues running the code, please create an issue in the GitHub repository explaining the problem, post in the discussion forum or if you are able to fix the code then please create a pull request and add to these help pages.

To clone the repository you will `git` installed and to then use the following command in a suitable directory:
`git clone https://github.com/EO-DataHub/eodh-training.git` 

The notebooks can be run anywhere that a Jupyter server is available. To use on the AppHub, download the required notebooks locally and then upload them using the upload button at the top-left of the AppHub window.

## Acronym list 

|Acronym | Meaning|
|----    |----    |
|ADES | Application Deployment and Execution Service (the EODH workflow runner)|
|ARD  | Analysis Ready Data (a pre-processed dataset) |
|AWS  | Amazon Web Services|
|CEDA | Centre for Environmental Data Analysis|
|CWL  | Common Workflow Language (a specification for standardising workflows)| 
|EO   | Earth observation |
|EODH | Earth observation Data Hub|
|WR   | Workflow Runner|
|YAML | Yet Another Markup Language (or YAML ain't markup language)|